In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.get_logger().setLevel('ERROR')

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns

from sklearn.model_selection import train_test_split

fig_dpi = 200

%load_ext tensorboard

# Scratchpad
Testbed

In [2]:
data = pd.read_csv('features.csv', header=None).T
data.columns = ['Clump thickness', 'Uniformity of cell size', 'Uniformity of cell shape', 'Marginal adhesion', 'Single epithelial cell size', 'Bare nuclei', 'Bland chomatin', 'Normal nucleoli', 'Mitoses']
labels = pd.read_csv('targets.csv', header=None).T
labels.columns = ['Benign', 'Malignant']

In [3]:
data_train, data_test, labels_train, labels_test = train_test_split(data, labels, test_size=0.5, random_state=70, stratify=labels)

In [4]:
layers = [tf.keras.layers.InputLayer(input_shape=(9,)), 
          tf.keras.layers.Dense(50, activation='sigmoid'), 
          tf.keras.layers.Dense(2, activation='softmax')]

model = tf.keras.models.Sequential(layers)
model.compile(tf.keras.optimizers.SGD(learning_rate=0.5, momentum=0.1), loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 50)                500       
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 102       
Total params: 602
Trainable params: 602
Non-trainable params: 0
_________________________________________________________________


In [5]:
model.fit(data_train, labels_train, epochs=10)

Epoch 1/10
11/11 [==============================] - 1s 2ms/step - loss: 1.3730 - accuracy: 0.5162
Epoch 2/10
11/11 [==============================] - 0s 3ms/step - loss: 0.7051 - accuracy: 0.6983
Epoch 3/10
11/11 [==============================] - 0s 2ms/step - loss: 0.3004 - accuracy: 0.8946
Epoch 4/10
11/11 [==============================] - 0s 2ms/step - loss: 0.1843 - accuracy: 0.9525
Epoch 5/10
11/11 [==============================] - 0s 2ms/step - loss: 0.1436 - accuracy: 0.9717
Epoch 6/10
11/11 [==============================] - 0s 2ms/step - loss: 0.1513 - accuracy: 0.9515
Epoch 7/10
11/11 [==============================] - 0s 2ms/step - loss: 0.1227 - accuracy: 0.9691
Epoch 8/10
11/11 [==============================] - 0s 2ms/step - loss: 0.1189 - accuracy: 0.9610
Epoch 9/10
11/11 [==============================] - 0s 2ms/step - loss: 0.1190 - accuracy: 0.9605
Epoch 10/10
11/11 [==============================] - 0s 2ms/step - loss: 0.1031 - accuracy: 0.9647


In [6]:
model.evaluate(data_test, 
               labels_test, 
               batch_size=128)

3/3 [==============================] - 0s 0s/step - loss: 0.1044 - accuracy: 0.9714


[0.10435652732849121, 0.9714285731315613]

In [9]:
tensor = model(data_test.to_numpy())

In [15]:
tensor

<tf.Tensor: shape=(350, 2), dtype=float32, numpy=
array([[9.58716929e-01, 4.12830450e-02],
       [9.82809603e-01, 1.71903893e-02],
       [9.17985260e-01, 8.20147023e-02],
       [1.16951922e-02, 9.88304853e-01],
       [9.08763647e-01, 9.12363231e-02],
       [9.70650494e-01, 2.93495078e-02],
       [5.17726317e-02, 9.48227346e-01],
       [5.00754118e-02, 9.49924529e-01],
       [9.82420444e-01, 1.75796002e-02],
       [9.79913116e-01, 2.00868454e-02],
       [9.62259054e-01, 3.77408862e-02],
       [9.82420444e-01, 1.75796002e-02],
       [9.75183308e-01, 2.48166639e-02],
       [9.75183308e-01, 2.48166639e-02],
       [9.58283842e-01, 4.17161174e-02],
       [9.76298213e-01, 2.37018093e-02],
       [5.01033245e-03, 9.94989693e-01],
       [9.38596308e-01, 6.14036731e-02],
       [9.82420444e-01, 1.75796002e-02],
       [3.77731547e-02, 9.62226868e-01],
       [9.84625578e-01, 1.53744193e-02],
       [2.63936166e-02, 9.73606348e-01],
       [9.58716929e-01, 4.12830450e-02],
       

In [16]:
tf.math.round(tensor)

<tf.Tensor: shape=(350, 2), dtype=float32, numpy=
array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]

In [31]:
tf.constant([1, 0]) + tf.constant([1, 0])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 0])>

In [20]:
tf.constant([1, 0]) == tf.constant([0, 1])

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False, False])>

In [32]:
for c in tf.constant(labels_test)[:5]:
    print(c)
    print(c == tf.constant([1, 0], dtype='int64'))
    print(tf.math.argmax(c))
    print()

tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor([ True  True], shape=(2,), dtype=bool)
tf.Tensor(0, shape=(), dtype=int64)

tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor([ True  True], shape=(2,), dtype=bool)
tf.Tensor(0, shape=(), dtype=int64)

tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor([ True  True], shape=(2,), dtype=bool)
tf.Tensor(0, shape=(), dtype=int64)

tf.Tensor([0 1], shape=(2,), dtype=int64)
tf.Tensor([False False], shape=(2,), dtype=bool)
tf.Tensor(1, shape=(), dtype=int64)

tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor([ True  True], shape=(2,), dtype=bool)
tf.Tensor(0, shape=(), dtype=int64)



In [30]:
tf.math.reduce_sum(tf.constant([[0, 1], [0, 1]]), axis=0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 2])>